### ISSUE TITLE
Rename this package into `ahmedshuhel:aurelia`

### ISSUE THREAD

**Issue by mquandalle** [ahmedshuhel/aurelia-meteor#1]
Hi,

It's generally useless to put the word `meteor` in the Meteor package name, because all packages there are for Meteor. One convention is too use the word `meteor` in the GitHub repository name, but not on atmosphere (eg https://github.com/mquandalle/meteor-jade vs https://atmospherejs.com/mquandalle/jade)

**Comment by ahmedshuhel** [comment]
@mquandalle Great suggestion. Will do that.

**Comment by ahmedshuhel** [comment]
@mquandalle is there any easy way to rename an existing package in atmosphere without creating a new one?

**Comment by mquandalle** [comment]
No, unfortunately.

**Comment by ahmedshuhel** [comment]
:( thanks for the info.

**Comment by ahmedshuhel** [comment]
The package is "renamed" and here is the [new link](https://atmospherejs.com/ahmedshuhel/aurelia). Thank you @mquandalle for your good advice.
